import useAppConfig from "@entities/app-config/model/useAppConfig";
import type { ReactNode } from "react";
import { useMemo } from "react";

import { AppConfigContext } from "@/context/AppConfigContext";

type AppConfigProviderProps = {
  children: ReactNode;
};

export function AppConfigProvider({ children }: AppConfigProviderProps) {
  const {
    config,
    loading,
    isConfigLoading,
    fetchConfig,
    saveConfig,
    getStartTime,
    getEndTime,
    getStandardWorkHours,
    getConfigId,
    getLinks,
    getReasons,
    getOfficeMode,
    getAttendanceStatisticsEnabled,
    getWorkflowNotificationEnabled,
    getTimeRecorderAnnouncement,
    getShiftCollaborativeEnabled,
    getShiftDefaultMode,
    getQuickInputStartTimes,
    getQuickInputEndTimes,
    getShiftGroups,
    getLunchRestStartTime,
    getLunchRestEndTime,
    getHourlyPaidHolidayEnabled,
    getAmHolidayStartTime,
    getAmHolidayEndTime,
    getPmHolidayStartTime,
    getPmHolidayEndTime,
    getAmPmHolidayEnabled,
    getSpecialHolidayEnabled,
    getAbsentEnabled,
    getOverTimeCheckEnabled,
    getWorkflowCategoryOrder,
    getThemeColor,
    getThemeTokens,
  } = useAppConfig();

  const derived = useMemo(
    () => ({
      startTime: getStartTime(),
      endTime: getEndTime(),
      standardWorkHours: getStandardWorkHours(),
      configId: getConfigId(),
      links: getLinks(),
      reasons: getReasons(),
      officeMode: getOfficeMode(),
      attendanceStatisticsEnabled: getAttendanceStatisticsEnabled(),
      workflowNotificationEnabled: getWorkflowNotificationEnabled(),
      timeRecorderAnnouncement: getTimeRecorderAnnouncement(),
      shiftCollaborativeEnabled: getShiftCollaborativeEnabled(),
      shiftDefaultMode: getShiftDefaultMode(),
      quickInputStartTimes: getQuickInputStartTimes(),
      quickInputEndTimes: getQuickInputEndTimes(),
      shiftGroups: getShiftGroups(),
      lunchRestStartTime: getLunchRestStartTime(),
      lunchRestEndTime: getLunchRestEndTime(),
      hourlyPaidHolidayEnabled: getHourlyPaidHolidayEnabled(),
      amHolidayStartTime: getAmHolidayStartTime(),
      amHolidayEndTime: getAmHolidayEndTime(),
      pmHolidayStartTime: getPmHolidayStartTime(),
      pmHolidayEndTime: getPmHolidayEndTime(),
      amPmHolidayEnabled: getAmPmHolidayEnabled(),
      specialHolidayEnabled: getSpecialHolidayEnabled?.() ?? false,
      absentEnabled: getAbsentEnabled?.() ?? false,
      overTimeCheckEnabled: getOverTimeCheckEnabled?.() ?? false,
      workflowCategoryOrder: getWorkflowCategoryOrder(),
      themeColor: getThemeColor(),
      themeTokens: getThemeTokens(),
    }),
    [
      getAbsentEnabled,
      getAmHolidayEndTime,
      getAmHolidayStartTime,
      getAmPmHolidayEnabled,
      getAttendanceStatisticsEnabled,
      getConfigId,
      getEndTime,
      getHourlyPaidHolidayEnabled,
      getLinks,
      getLunchRestEndTime,
      getLunchRestStartTime,
      getOfficeMode,
      getOverTimeCheckEnabled,
      getPmHolidayEndTime,
      getPmHolidayStartTime,
      getQuickInputEndTimes,
      getQuickInputStartTimes,
      getReasons,
      getShiftCollaborativeEnabled,
      getShiftDefaultMode,
      getShiftGroups,
      getSpecialHolidayEnabled,
      getStandardWorkHours,
      getStartTime,
      getThemeColor,
      getThemeTokens,
      getTimeRecorderAnnouncement,
      getWorkflowCategoryOrder,
      getWorkflowNotificationEnabled,
    ],
  );

  const value = useMemo(
    () => ({
      config,
      derived,
      loading,
      isLoading: isConfigLoading,
      isConfigLoading,
      refetch: fetchConfig,
      save: saveConfig,
      fetchConfig,
      saveConfig,
      getStartTime,
      getEndTime,
      getStandardWorkHours,
      getConfigId,
      getLinks,
      getReasons,
      getOfficeMode,
      getAttendanceStatisticsEnabled,
      getWorkflowNotificationEnabled,
      getTimeRecorderAnnouncement,
      getShiftCollaborativeEnabled,
      getShiftDefaultMode,
      getQuickInputStartTimes,
      getQuickInputEndTimes,
      getShiftGroups,
      getLunchRestStartTime,
      getLunchRestEndTime,
      getHourlyPaidHolidayEnabled,
      getAmHolidayStartTime,
      getAmHolidayEndTime,
      getPmHolidayStartTime,
      getPmHolidayEndTime,
      getAmPmHolidayEnabled,
      getSpecialHolidayEnabled,
      getAbsentEnabled,
      getOverTimeCheckEnabled,
      getWorkflowCategoryOrder,
      getThemeColor,
      getThemeTokens,
    }),
    [
      config,
      derived,
      fetchConfig,
      getAbsentEnabled,
      getAmHolidayEndTime,
      getAmHolidayStartTime,
      getAmPmHolidayEnabled,
      getAttendanceStatisticsEnabled,
      getConfigId,
      getEndTime,
      getHourlyPaidHolidayEnabled,
      getLinks,
      getLunchRestEndTime,
      getLunchRestStartTime,
      getOfficeMode,
      getOverTimeCheckEnabled,
      getPmHolidayEndTime,
      getPmHolidayStartTime,
      getQuickInputEndTimes,
      getQuickInputStartTimes,
      getReasons,
      getShiftCollaborativeEnabled,
      getShiftDefaultMode,
      getShiftGroups,
      getSpecialHolidayEnabled,
      getStandardWorkHours,
      getStartTime,
      getThemeColor,
      getThemeTokens,
      getTimeRecorderAnnouncement,
      getWorkflowCategoryOrder,
      getWorkflowNotificationEnabled,
      isConfigLoading,
      loading,
      saveConfig,
    ],
  );

  return (
    <AppConfigContext.Provider value={value}>
      {children}
    </AppConfigContext.Provider>
  );
}
